global using Xunit;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using OrdenesInversion.Contracts.Cuenta;
global using OrdenesInversion.Services.Cuentas;
global using OrdenesInversion.Contracts.Orden;
global using OrdenesInversion.Data;
global using OrdenesInversion.Services.Ordenes;
global using OrdenesInversion.Controllers;